version: '3.4'

services:
  delailahrestoapi:
    depends_on: 
      - cache
    image: delilachinicola
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: 
      - .env
    environment:
     - REDIS_URL=redis://cache:6379
     - CALLBACK_URL_GITHUB=http://localhost:3000/api/v2/auth/github/callback
     - CALLBACK_URL_LINKEDIN=http://localhost:3000/api/v2/auth/linkedin/callback
     - CALLBACK_URL_GOOGLE=http://localhost:3000/api/v2/auth/google/callback
    ports:
      - 3000:3000
  
  cache:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
