openapi: 3.0.0
info:
  title: Delaila Resto API
  description: API de Delailah Resto para presentar en Sprint Proyect 2 de Acamica.
  version: 2.0.0
servers:
  - url: http://localhost:3000/api/v2
    description: Server de prueba
tags:
  - name: Usuarios
    description: Seccion Usuarios
  - name: Pedidos
    description: Todo sobre tus pedidos
  - name: Productos
    description: Todo sobre los Productos de Delailah Resto
  - name: Only admins
    description: Acciones solo para administradores
components:
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT    
paths:
  /users/register:
    post:
      tags:
      - "Usuarios"
      summary: Registro de un nuevo usuario.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: usuario1
                password:
                  type: string
                  example: bartsimpson123
                nombre:
                  type: string
                  example: usuario
                apellido:
                  type: string
                  example: 1
                direccion:
                  type: string
                  example: direccion de ejemplo
                telefono:
                  type: string
                  example: 123123123
                email:
                  type: string
                  example: usuario@examples.com
      responses:
        '201':   #status code
          description: User created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: El id del usuario creado
        default:
          description: Unexpected error
  /users/login:
    post:
      tags:
      - "Usuarios"
      summary: Login de un usuario.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: usuario1
                password:
                  type: string
                  example: bartsimpson123
      responses:
        '202':    # status code
          description: Login exitoso
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                    description: JWT signature
        '400':
          description: Error en usuario o contraseña.
        default:
          description: Unexpected error
  /pedidos:
    get:
      security:
        - bearerAuth: []
      tags:
      - "Pedidos"
      summary: Obtener listado de pedidos.
      responses:
        '200':    # status code
          description: Listado de pedidos
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
        default:
          description: Unexpected error
    post:
      security:
        - bearerAuth: []
      tags:
      - "Pedidos"
      summary: Nuevo pedido.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                direccionenvio:
                  type: string
                  example: Av siempreviva 123
                payment:
                  type: string
                  example: efectivo
                subpedido:
                  type: array
                  items:
                    type: object
                    properties:
                      idproducto:
                        type: number
                        example: 620cc116bb519646507cfec4
                      cant:
                        type: number
                        example: 3
              required:
                - payment
                - subpedido           
      responses:
        '201':    # status code
          description: Pedido creado
          content:
            application/json:
              schema: 
                type: object
                items: 
                  type: string
        default:
          description: Unexpected error
  /pedido/{idpedido}:
    put:
      security:
        - bearerAuth: []
      tags:
      - "Pedidos"
      summary: Actualizar pedido.
      parameters:
        - in: path
          name: idpedido
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subpedido:
                  type: array
                  items:
                    type: object
                    properties:
                      idproducto:
                        type: string
                        example: 620cc116bb519646507cfec4
                      cant:
                        type: number
                        example: 3
      responses:
        '200':    # status code
          description: Pedido actualizado
          content:
            application/json:
              schema: 
                type: object
        default:
          description: Unexpected error
    delete:
      security:
        - bearerAuth: []
      tags:
      - "Pedidos"
      summary: Cancelar un pedido.
      parameters:
        - in: path
          name: idpedido
          schema:
            type: string
          required: true
      responses:
        '204':    # status code
          description: Pedido eliminado
          content:
            application/json:
              schema: 
                type: string
                items: 
                  type: string
        default:
          description: Unexpected error
  /pedido/{idpedido}/confirm:
    put:
      security:
        - bearerAuth: []
      tags:
      - "Pedidos"
      summary: Confirmar el pedido.
      parameters:
        - in: path
          name: idpedido
          schema:
            type: string
          required: true
      responses:
        '200':    # status code
          description: Pedido actualizado
          content:
            application/json:
              schema: 
                type: object
                items: 
                  type: string
        '401':
          description: The specified user ID is invalid (not a number).
        default:
          description: Unexpected error
  /admin/pedido/{idpedido}/?newstatus:
    put:
      security:
        - bearerAuth: []
      tags:
      - "Only admins"
      summary: Cambiar estado pedido.
      parameters:
        - in: path
          name: idpedido
          schema:
            type: string
          required: true
        - in: query
          name: newstatus
          schema:
            type: string
            enum:
              - En preparacion
              - Enviado
              - Entregado
          allowReserved: true
      responses:
        '200':    # status code
          description: Pedido actualizado
          content:
            application/json:
              schema: 
                type: object
        default:
          description: Unexpected error
  /productos:
    get:
      tags:
      - "Productos"
      summary: Buscar un producto.
      parameters:
        - in: query
          name: idproducto
          schema:
            type: string
          required: false
      responses:
        '200':    # status code
          description: Producto buscado
          content:
            application/json:
              schema: 
                type: object
                properties:
                  id:
                    type: number
                  nombre:
                    type: string
                  descripcion:
                    type: string
                  precio:
                    type: number
        default:
          description: Unexpected error
  /admin/productos:
    post:
      security:
        - bearerAuth: []
      tags:
      - "Only admins"
      summary: Nuevo Producto (requiere administrador).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: platoX
                descripcion:
                  type: string
                  example: Descripcion del plato
                precio:
                  type: number
                  example: 123
      responses:
        '201':    # status code
          description: Producto creado
          content:
            application/json:
              schema: 
                type: object
        default:
          description: Unexpected error
  /admin/productos/{idproducto}:
    put:
      security:
        - bearerAuth: []
      tags:
      - "Only admins"
      summary: Actualizar Producto (requiere administrador).
      parameters:
        - in: path
          name: idproducto
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                descripcion:
                  type: string
                  example: Descripcion del producto
                precio:
                  type: number
                  example: 123  
      responses:
        '200':    # status code
          description: Producto actualizado
          content:
            application/json:
              schema: 
                type: object
                properties:
                  descripcion:
                    type: string
                  precio:
                    type: number
        default:
          description: Unexpected error
    delete:
      security:
        - bearerAuth: []
      tags:
      - "Only admins"
      summary: Eliminar Producto (requiere administrador).
      parameters:
        - in: path
          name: idproducto
          schema:
            type: string
          required: true
      responses:
        '204':    # status code
          description: Producto eliminado
          content:
            application/json:
              schema: 
                type: string
        default:
          description: Unexpected error
  /admin/payments:
    get:
      security:
        - bearerAuth: []
      tags:
        - "Only admins"
      summary: Muestra todos los medios de pago disponible (requiere administrador).
      responses:
        '200':
          description: Medios de pago disponible
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name: 
                      type: string
                      description: Nombre del medio de pago
                    descripcion:
                      type: string
                      description: Descripcion del medio de pago
    post:
      security:
        - bearerAuth: []
      tags:
        - "Only admins"
      summary: Agregar un nuevo medio de pago (requiere administrador).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                descripcion:
                  type: string    
      responses:
        '201':
          description: Medio de pago creado
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  descripcion: 
                    type: string
  /admin/payments/{idpayment}:
    put:
      security:
        - bearerAuth: []
      tags:
        - "Only admins"
      summary: Actualiza un medio de pago (requiere administrador).
      parameters:
        - in: path
          name: idpayment
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                descripcion:
                  type: string
      responses:
        '200':
          description: Medios de pago actualizado
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    delete:
      security:
        - bearerAuth: []
      tags:
        - "Only admins"
      summary: Elimina un medio de pago (requiere administrador).
      parameters:
        - in: path
          name: idpayment
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Medio de pago eliminado
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /admin/users:
    get:
      security:
        - bearerAuth: []
      tags:
        - "Only admins"
      summary: Muestra todos los usuarios (requiere administrador).
      responses:
        '200':
          description: Usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /admin/users/{userid}:
    get:
      security:
        - bearerAuth: []
      tags:
        - "Only admins"
      summary: Muestra a un usuario (requiere administrado).
      parameters:
        - in: path
          name: userid
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Usuario/os
          content:
            application/json:
              schema:
                type: object
  /admin/users/{userid}/suspend:
    put:
      security:
        - bearerAuth: []
      tags:
        - "Only admins"
      summary: Muestra a un usuario o a todos los usuarios (requiere administrado).
      parameters:
        - in: path
          name: userid
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Suspende al usuario
          content:
            application/json:
              schema:
                type: string